/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'totalRevenueNPR' : bigint,
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'confirmedOrders' : bigint,
  'deliveredOrders' : bigint,
}
export type Category = { 'Streaming' : null } |
  { 'Software' : null } |
  { 'Gaming' : null };
export interface CreateOrderInput {
  'paymentMethod' : PaymentMethod,
  'userEmail' : string,
  'totalNPR' : bigint,
  'items' : Array<OrderItem>,
}
export interface CreateProductInput {
  'featured' : boolean,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'priceNPR' : bigint,
}
export interface DailyRevenue {
  'revenueNPR' : bigint,
  'date' : string,
  'orderCount' : bigint,
}
export type LoginResult = {
    'ok' : { 'token' : SessionToken, 'user' : UserInfo }
  } |
  { 'err' : string };
export interface OrderFilter {
  'status' : [] | [PaymentStatus],
  'productName' : [] | [string],
  'email' : [] | [string],
}
export type OrderId = string;
export interface OrderInfo {
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'userEmail' : string,
  'orderId' : OrderId,
  'totalNPR' : bigint,
  'timestamp' : Timestamp,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'productName' : string,
  'priceNPR' : bigint,
}
export type PaymentMethod = { 'BankTransfer' : null } |
  { 'ESewa' : null };
export type PaymentStatus = { 'UnderReview' : null } |
  { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Processing' : null };
export interface ProductInfo {
  'id' : bigint,
  'featured' : boolean,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'priceNPR' : bigint,
}
export type SessionToken = string;
export interface StatusDistribution {
  'underReview' : bigint,
  'delivered' : bigint,
  'confirmed' : bigint,
  'processing' : bigint,
}
export type Timestamp = bigint;
export interface TopProduct {
  'revenueNPR' : bigint,
  'productId' : bigint,
  'productName' : string,
  'orderCount' : bigint,
}
export interface UpdateProductInput {
  'featured' : [] | [boolean],
  'inStock' : [] | [boolean],
  'name' : [] | [string],
  'description' : [] | [string],
  'imageUrl' : [] | [string],
  'category' : [] | [Category],
  'priceNPR' : [] | [bigint],
}
export interface UserInfo {
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'user' : null } |
  { 'staff' : null };
export interface _SERVICE {
  'createOrder' : ActorMethod<
    [SessionToken, CreateOrderInput],
    { 'ok' : OrderInfo } |
      { 'err' : string }
  >,
  'createProduct' : ActorMethod<
    [SessionToken, CreateProductInput],
    { 'ok' : ProductInfo } |
      { 'err' : string }
  >,
  'deleteProduct' : ActorMethod<
    [SessionToken, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAllOrders' : ActorMethod<
    [SessionToken],
    { 'ok' : Array<OrderInfo> } |
      { 'err' : string }
  >,
  'getAnalyticsSummary' : ActorMethod<
    [SessionToken],
    { 'ok' : AnalyticsSummary } |
      { 'err' : string }
  >,
  'getDailyRevenue' : ActorMethod<
    [SessionToken],
    { 'ok' : Array<DailyRevenue> } |
      { 'err' : string }
  >,
  'getMe' : ActorMethod<[SessionToken], [] | [UserInfo]>,
  'getMyOrders' : ActorMethod<
    [SessionToken],
    { 'ok' : Array<OrderInfo> } |
      { 'err' : string }
  >,
  'getProduct' : ActorMethod<[bigint], [] | [ProductInfo]>,
  'getProducts' : ActorMethod<[], Array<ProductInfo>>,
  'getStatusDistribution' : ActorMethod<
    [SessionToken],
    { 'ok' : StatusDistribution } |
      { 'err' : string }
  >,
  'getTopProducts' : ActorMethod<
    [SessionToken, bigint],
    { 'ok' : Array<TopProduct> } |
      { 'err' : string }
  >,
  'login' : ActorMethod<[string, string], LoginResult>,
  'logout' : ActorMethod<[SessionToken], undefined>,
  'searchOrders' : ActorMethod<
    [SessionToken, OrderFilter],
    { 'ok' : Array<OrderInfo> } |
      { 'err' : string }
  >,
  'signUp' : ActorMethod<[string, string], LoginResult>,
  'staffLogin' : ActorMethod<[string, string], LoginResult>,
  'toggleStock' : ActorMethod<
    [SessionToken, bigint],
    { 'ok' : ProductInfo } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [SessionToken, OrderId, PaymentStatus],
    { 'ok' : OrderInfo } |
      { 'err' : string }
  >,
  'updateProduct' : ActorMethod<
    [SessionToken, bigint, UpdateProductInput],
    { 'ok' : ProductInfo } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];