/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionToken = IDL.Text;
export const PaymentMethod = IDL.Variant({
  'BankTransfer' : IDL.Null,
  'ESewa' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'priceNPR' : IDL.Nat,
});
export const CreateOrderInput = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'userEmail' : IDL.Text,
  'totalNPR' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const PaymentStatus = IDL.Variant({
  'UnderReview' : IDL.Null,
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Processing' : IDL.Null,
});
export const OrderId = IDL.Text;
export const Timestamp = IDL.Int;
export const OrderInfo = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'userEmail' : IDL.Text,
  'orderId' : OrderId,
  'totalNPR' : IDL.Nat,
  'timestamp' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});
export const Category = IDL.Variant({
  'Streaming' : IDL.Null,
  'Software' : IDL.Null,
  'Gaming' : IDL.Null,
});
export const CreateProductInput = IDL.Record({
  'featured' : IDL.Bool,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'priceNPR' : IDL.Nat,
});
export const ProductInfo = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'priceNPR' : IDL.Nat,
});
export const AnalyticsSummary = IDL.Record({
  'totalRevenueNPR' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'confirmedOrders' : IDL.Nat,
  'deliveredOrders' : IDL.Nat,
});
export const DailyRevenue = IDL.Record({
  'revenueNPR' : IDL.Nat,
  'date' : IDL.Text,
  'orderCount' : IDL.Nat,
});
export const UserRole = IDL.Variant({ 'user' : IDL.Null, 'staff' : IDL.Null });
export const UserInfo = IDL.Record({
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const StatusDistribution = IDL.Record({
  'underReview' : IDL.Nat,
  'delivered' : IDL.Nat,
  'confirmed' : IDL.Nat,
  'processing' : IDL.Nat,
});
export const TopProduct = IDL.Record({
  'revenueNPR' : IDL.Nat,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'orderCount' : IDL.Nat,
});
export const LoginResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : SessionToken, 'user' : UserInfo }),
  'err' : IDL.Text,
});
export const OrderFilter = IDL.Record({
  'status' : IDL.Opt(PaymentStatus),
  'productName' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
});
export const UpdateProductInput = IDL.Record({
  'featured' : IDL.Opt(IDL.Bool),
  'inStock' : IDL.Opt(IDL.Bool),
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
  'priceNPR' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'createOrder' : IDL.Func(
      [SessionToken, CreateOrderInput],
      [IDL.Variant({ 'ok' : OrderInfo, 'err' : IDL.Text })],
      [],
    ),
  'createProduct' : IDL.Func(
      [SessionToken, CreateProductInput],
      [IDL.Variant({ 'ok' : ProductInfo, 'err' : IDL.Text })],
      [],
    ),
  'deleteProduct' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAllOrders' : IDL.Func(
      [SessionToken],
      [IDL.Variant({ 'ok' : IDL.Vec(OrderInfo), 'err' : IDL.Text })],
      ['query'],
    ),
  'getAnalyticsSummary' : IDL.Func(
      [SessionToken],
      [IDL.Variant({ 'ok' : AnalyticsSummary, 'err' : IDL.Text })],
      ['query'],
    ),
  'getDailyRevenue' : IDL.Func(
      [SessionToken],
      [IDL.Variant({ 'ok' : IDL.Vec(DailyRevenue), 'err' : IDL.Text })],
      ['query'],
    ),
  'getMe' : IDL.Func([SessionToken], [IDL.Opt(UserInfo)], ['query']),
  'getMyOrders' : IDL.Func(
      [SessionToken],
      [IDL.Variant({ 'ok' : IDL.Vec(OrderInfo), 'err' : IDL.Text })],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(ProductInfo)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(ProductInfo)], ['query']),
  'getStatusDistribution' : IDL.Func(
      [SessionToken],
      [IDL.Variant({ 'ok' : StatusDistribution, 'err' : IDL.Text })],
      ['query'],
    ),
  'getTopProducts' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(TopProduct), 'err' : IDL.Text })],
      ['query'],
    ),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([SessionToken], [], []),
  'searchOrders' : IDL.Func(
      [SessionToken, OrderFilter],
      [IDL.Variant({ 'ok' : IDL.Vec(OrderInfo), 'err' : IDL.Text })],
      ['query'],
    ),
  'signUp' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'staffLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'toggleStock' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Variant({ 'ok' : ProductInfo, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [SessionToken, OrderId, PaymentStatus],
      [IDL.Variant({ 'ok' : OrderInfo, 'err' : IDL.Text })],
      [],
    ),
  'updateProduct' : IDL.Func(
      [SessionToken, IDL.Nat, UpdateProductInput],
      [IDL.Variant({ 'ok' : ProductInfo, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionToken = IDL.Text;
  const PaymentMethod = IDL.Variant({
    'BankTransfer' : IDL.Null,
    'ESewa' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'priceNPR' : IDL.Nat,
  });
  const CreateOrderInput = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'userEmail' : IDL.Text,
    'totalNPR' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const PaymentStatus = IDL.Variant({
    'UnderReview' : IDL.Null,
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Processing' : IDL.Null,
  });
  const OrderId = IDL.Text;
  const Timestamp = IDL.Int;
  const OrderInfo = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'userEmail' : IDL.Text,
    'orderId' : OrderId,
    'totalNPR' : IDL.Nat,
    'timestamp' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  const Category = IDL.Variant({
    'Streaming' : IDL.Null,
    'Software' : IDL.Null,
    'Gaming' : IDL.Null,
  });
  const CreateProductInput = IDL.Record({
    'featured' : IDL.Bool,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'priceNPR' : IDL.Nat,
  });
  const ProductInfo = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'priceNPR' : IDL.Nat,
  });
  const AnalyticsSummary = IDL.Record({
    'totalRevenueNPR' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'confirmedOrders' : IDL.Nat,
    'deliveredOrders' : IDL.Nat,
  });
  const DailyRevenue = IDL.Record({
    'revenueNPR' : IDL.Nat,
    'date' : IDL.Text,
    'orderCount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({ 'user' : IDL.Null, 'staff' : IDL.Null });
  const UserInfo = IDL.Record({
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const StatusDistribution = IDL.Record({
    'underReview' : IDL.Nat,
    'delivered' : IDL.Nat,
    'confirmed' : IDL.Nat,
    'processing' : IDL.Nat,
  });
  const TopProduct = IDL.Record({
    'revenueNPR' : IDL.Nat,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'orderCount' : IDL.Nat,
  });
  const LoginResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : SessionToken, 'user' : UserInfo }),
    'err' : IDL.Text,
  });
  const OrderFilter = IDL.Record({
    'status' : IDL.Opt(PaymentStatus),
    'productName' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
  });
  const UpdateProductInput = IDL.Record({
    'featured' : IDL.Opt(IDL.Bool),
    'inStock' : IDL.Opt(IDL.Bool),
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
    'priceNPR' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'createOrder' : IDL.Func(
        [SessionToken, CreateOrderInput],
        [IDL.Variant({ 'ok' : OrderInfo, 'err' : IDL.Text })],
        [],
      ),
    'createProduct' : IDL.Func(
        [SessionToken, CreateProductInput],
        [IDL.Variant({ 'ok' : ProductInfo, 'err' : IDL.Text })],
        [],
      ),
    'deleteProduct' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAllOrders' : IDL.Func(
        [SessionToken],
        [IDL.Variant({ 'ok' : IDL.Vec(OrderInfo), 'err' : IDL.Text })],
        ['query'],
      ),
    'getAnalyticsSummary' : IDL.Func(
        [SessionToken],
        [IDL.Variant({ 'ok' : AnalyticsSummary, 'err' : IDL.Text })],
        ['query'],
      ),
    'getDailyRevenue' : IDL.Func(
        [SessionToken],
        [IDL.Variant({ 'ok' : IDL.Vec(DailyRevenue), 'err' : IDL.Text })],
        ['query'],
      ),
    'getMe' : IDL.Func([SessionToken], [IDL.Opt(UserInfo)], ['query']),
    'getMyOrders' : IDL.Func(
        [SessionToken],
        [IDL.Variant({ 'ok' : IDL.Vec(OrderInfo), 'err' : IDL.Text })],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(ProductInfo)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(ProductInfo)], ['query']),
    'getStatusDistribution' : IDL.Func(
        [SessionToken],
        [IDL.Variant({ 'ok' : StatusDistribution, 'err' : IDL.Text })],
        ['query'],
      ),
    'getTopProducts' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(TopProduct), 'err' : IDL.Text })],
        ['query'],
      ),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([SessionToken], [], []),
    'searchOrders' : IDL.Func(
        [SessionToken, OrderFilter],
        [IDL.Variant({ 'ok' : IDL.Vec(OrderInfo), 'err' : IDL.Text })],
        ['query'],
      ),
    'signUp' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'staffLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'toggleStock' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Variant({ 'ok' : ProductInfo, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [SessionToken, OrderId, PaymentStatus],
        [IDL.Variant({ 'ok' : OrderInfo, 'err' : IDL.Text })],
        [],
      ),
    'updateProduct' : IDL.Func(
        [SessionToken, IDL.Nat, UpdateProductInput],
        [IDL.Variant({ 'ok' : ProductInfo, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };