/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductInfo {
    id: bigint;
    featured: boolean;
    inStock: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    priceNPR: bigint;
}
export type Timestamp = bigint;
export interface AnalyticsSummary {
    totalRevenueNPR: bigint;
    totalOrders: bigint;
    pendingOrders: bigint;
    confirmedOrders: bigint;
    deliveredOrders: bigint;
}
export interface OrderItem {
    productId: bigint;
    productName: string;
    priceNPR: bigint;
}
export interface UserInfo {
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}
export interface UpdateProductInput {
    featured?: boolean;
    inStock?: boolean;
    name?: string;
    description?: string;
    imageUrl?: string;
    category?: Category;
    priceNPR?: bigint;
}
export interface DailyRevenue {
    revenueNPR: bigint;
    date: string;
    orderCount: bigint;
}
export interface CreateProductInput {
    featured: boolean;
    inStock: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    priceNPR: bigint;
}
export interface TopProduct {
    revenueNPR: bigint;
    productId: bigint;
    productName: string;
    orderCount: bigint;
}
export interface OrderInfo {
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    userEmail: string;
    orderId: OrderId;
    totalNPR: bigint;
    timestamp: Timestamp;
    items: Array<OrderItem>;
}
export type SessionToken = string;
export interface StatusDistribution {
    underReview: bigint;
    delivered: bigint;
    confirmed: bigint;
    processing: bigint;
}
export interface CreateOrderInput {
    paymentMethod: PaymentMethod;
    userEmail: string;
    totalNPR: bigint;
    items: Array<OrderItem>;
}
export interface OrderFilter {
    status?: PaymentStatus;
    productName?: string;
    email?: string;
}
export type LoginResult = {
    __kind__: "ok";
    ok: {
        token: SessionToken;
        user: UserInfo;
    };
} | {
    __kind__: "err";
    err: string;
};
export type OrderId = string;
export enum Category {
    Streaming = "Streaming",
    Software = "Software",
    Gaming = "Gaming"
}
export enum PaymentMethod {
    BankTransfer = "BankTransfer",
    ESewa = "ESewa"
}
export enum PaymentStatus {
    UnderReview = "UnderReview",
    Delivered = "Delivered",
    Confirmed = "Confirmed",
    Processing = "Processing"
}
export enum UserRole {
    user = "user",
    staff = "staff"
}
export interface backendInterface {
    createOrder(token: SessionToken, input: CreateOrderInput): Promise<{
        __kind__: "ok";
        ok: OrderInfo;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createProduct(token: SessionToken, input: CreateProductInput): Promise<{
        __kind__: "ok";
        ok: ProductInfo;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteProduct(token: SessionToken, id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllOrders(token: SessionToken): Promise<{
        __kind__: "ok";
        ok: Array<OrderInfo>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAnalyticsSummary(token: SessionToken): Promise<{
        __kind__: "ok";
        ok: AnalyticsSummary;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getDailyRevenue(token: SessionToken): Promise<{
        __kind__: "ok";
        ok: Array<DailyRevenue>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMe(token: SessionToken): Promise<UserInfo | null>;
    getMyOrders(token: SessionToken): Promise<{
        __kind__: "ok";
        ok: Array<OrderInfo>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getProduct(id: bigint): Promise<ProductInfo | null>;
    getProducts(): Promise<Array<ProductInfo>>;
    getStatusDistribution(token: SessionToken): Promise<{
        __kind__: "ok";
        ok: StatusDistribution;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getTopProducts(token: SessionToken, limit: bigint): Promise<{
        __kind__: "ok";
        ok: Array<TopProduct>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    login(email: string, password: string): Promise<LoginResult>;
    logout(token: SessionToken): Promise<void>;
    searchOrders(token: SessionToken, filter: OrderFilter): Promise<{
        __kind__: "ok";
        ok: Array<OrderInfo>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    signUp(email: string, password: string): Promise<LoginResult>;
    staffLogin(email: string, staffCode: string): Promise<LoginResult>;
    toggleStock(token: SessionToken, id: bigint): Promise<{
        __kind__: "ok";
        ok: ProductInfo;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateOrderStatus(token: SessionToken, orderId: OrderId, newStatus: PaymentStatus): Promise<{
        __kind__: "ok";
        ok: OrderInfo;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateProduct(token: SessionToken, id: bigint, input: UpdateProductInput): Promise<{
        __kind__: "ok";
        ok: ProductInfo;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AnalyticsSummary as _AnalyticsSummary, Category as _Category, CreateOrderInput as _CreateOrderInput, CreateProductInput as _CreateProductInput, DailyRevenue as _DailyRevenue, LoginResult as _LoginResult, OrderFilter as _OrderFilter, OrderId as _OrderId, OrderInfo as _OrderInfo, OrderItem as _OrderItem, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, ProductInfo as _ProductInfo, SessionToken as _SessionToken, StatusDistribution as _StatusDistribution, Timestamp as _Timestamp, TopProduct as _TopProduct, UpdateProductInput as _UpdateProductInput, UserInfo as _UserInfo, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createOrder(arg0: SessionToken, arg1: CreateOrderInput): Promise<{
        __kind__: "ok";
        ok: OrderInfo;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, to_candid_CreateOrderInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, to_candid_CreateOrderInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: SessionToken, arg1: CreateProductInput): Promise<{
        __kind__: "ok";
        ok: ProductInfo;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, to_candid_CreateProductInput_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, to_candid_CreateProductInput_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: SessionToken, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0, arg1);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0, arg1);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(arg0: SessionToken): Promise<{
        __kind__: "ok";
        ok: Array<OrderInfo>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders(arg0);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders(arg0);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsSummary(arg0: SessionToken): Promise<{
        __kind__: "ok";
        ok: AnalyticsSummary;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary(arg0);
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary(arg0);
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyRevenue(arg0: SessionToken): Promise<{
        __kind__: "ok";
        ok: Array<DailyRevenue>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyRevenue(arg0);
                return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyRevenue(arg0);
            return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMe(arg0: SessionToken): Promise<UserInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMe(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMe(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(arg0: SessionToken): Promise<{
        __kind__: "ok";
        ok: Array<OrderInfo>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders(arg0);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders(arg0);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<ProductInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<ProductInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatusDistribution(arg0: SessionToken): Promise<{
        __kind__: "ok";
        ok: StatusDistribution;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatusDistribution(arg0);
                return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatusDistribution(arg0);
            return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopProducts(arg0: SessionToken, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: Array<TopProduct>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopProducts(arg0, arg1);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopProducts(arg0, arg1);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async searchOrders(arg0: SessionToken, arg1: OrderFilter): Promise<{
        __kind__: "ok";
        ok: Array<OrderInfo>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.searchOrders(arg0, to_candid_OrderFilter_n38(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchOrders(arg0, to_candid_OrderFilter_n38(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async signUp(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.signUp(arg0, arg1);
                return from_candid_LoginResult_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signUp(arg0, arg1);
            return from_candid_LoginResult_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async staffLogin(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.staffLogin(arg0, arg1);
                return from_candid_LoginResult_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.staffLogin(arg0, arg1);
            return from_candid_LoginResult_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleStock(arg0: SessionToken, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: ProductInfo;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleStock(arg0, arg1);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleStock(arg0, arg1);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: SessionToken, arg1: OrderId, arg2: PaymentStatus): Promise<{
        __kind__: "ok";
        ok: OrderInfo;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1, to_candid_PaymentStatus_n40(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1, to_candid_PaymentStatus_n40(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: SessionToken, arg1: bigint, arg2: UpdateProductInput): Promise<{
        __kind__: "ok";
        ok: ProductInfo;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, to_candid_UpdateProductInput_n42(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, to_candid_UpdateProductInput_n42(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_OrderInfo_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderInfo): OrderInfo {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ProductInfo_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductInfo): ProductInfo {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserInfo_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserInfo): UserInfo {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserInfo]): UserInfo | null {
    return value.length === 0 ? null : from_candid_UserInfo_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductInfo]): ProductInfo | null {
    return value.length === 0 ? null : from_candid_ProductInfo_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    featured: boolean;
    inStock: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    priceNPR: bigint;
}): {
    id: bigint;
    featured: boolean;
    inStock: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    priceNPR: bigint;
} {
    return {
        id: value.id,
        featured: value.featured,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_Category_n19(_uploadFile, _downloadFile, value.category),
        priceNPR: value.priceNPR
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
}): {
    createdAt: Timestamp;
    role: UserRole;
    email: string;
} {
    return {
        createdAt: value.createdAt,
        role: from_candid_UserRole_n29(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: _SessionToken;
    user: _UserInfo;
}): {
    token: SessionToken;
    user: UserInfo;
} {
    return {
        token: value.token,
        user: from_candid_UserInfo_n27(_uploadFile, _downloadFile, value.user)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: _PaymentStatus;
    paymentMethod: _PaymentMethod;
    userEmail: string;
    orderId: _OrderId;
    totalNPR: bigint;
    timestamp: _Timestamp;
    items: Array<_OrderItem>;
}): {
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    userEmail: string;
    orderId: OrderId;
    totalNPR: bigint;
    timestamp: Timestamp;
    items: Array<OrderItem>;
} {
    return {
        paymentStatus: from_candid_PaymentStatus_n8(_uploadFile, _downloadFile, value.paymentStatus),
        paymentMethod: from_candid_PaymentMethod_n10(_uploadFile, _downloadFile, value.paymentMethod),
        userEmail: value.userEmail,
        orderId: value.orderId,
        totalNPR: value.totalNPR,
        timestamp: value.timestamp,
        items: value.items
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BankTransfer: null;
} | {
    ESewa: null;
}): PaymentMethod {
    return "BankTransfer" in value ? PaymentMethod.BankTransfer : "ESewa" in value ? PaymentMethod.ESewa : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ProductInfo;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ProductInfo;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ProductInfo_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Streaming: null;
} | {
    Software: null;
} | {
    Gaming: null;
}): Category {
    return "Streaming" in value ? Category.Streaming : "Software" in value ? Category.Software : "Gaming" in value ? Category.Gaming : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_OrderInfo>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<OrderInfo>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n23(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AnalyticsSummary;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AnalyticsSummary;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_DailyRevenue>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<DailyRevenue>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    staff: null;
}): UserRole {
    return "user" in value ? UserRole.user : "staff" in value ? UserRole.staff : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StatusDistribution;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StatusDistribution;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_TopProduct>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<TopProduct>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: _SessionToken;
        user: _UserInfo;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        token: SessionToken;
        user: UserInfo;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n37(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _OrderInfo;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: OrderInfo;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_OrderInfo_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UnderReview: null;
} | {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Processing: null;
}): PaymentStatus {
    return "UnderReview" in value ? PaymentStatus.UnderReview : "Delivered" in value ? PaymentStatus.Delivered : "Confirmed" in value ? PaymentStatus.Confirmed : "Processing" in value ? PaymentStatus.Processing : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderInfo>): Array<OrderInfo> {
    return value.map((x)=>from_candid_OrderInfo_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductInfo>): Array<ProductInfo> {
    return value.map((x)=>from_candid_ProductInfo_n17(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_CreateOrderInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderInput): _CreateOrderInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProductInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductInput): _CreateProductInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_OrderFilter_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderFilter): _OrderFilter {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProductInput_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProductInput): _UpdateProductInput {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featured: boolean;
    inStock: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    priceNPR: bigint;
}): {
    featured: boolean;
    inStock: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    priceNPR: bigint;
} {
    return {
        featured: value.featured,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: to_candid_Category_n14(_uploadFile, _downloadFile, value.category),
        priceNPR: value.priceNPR
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    userEmail: string;
    totalNPR: bigint;
    items: Array<OrderItem>;
}): {
    paymentMethod: _PaymentMethod;
    userEmail: string;
    totalNPR: bigint;
    items: Array<_OrderItem>;
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n3(_uploadFile, _downloadFile, value.paymentMethod),
        userEmail: value.userEmail,
        totalNPR: value.totalNPR,
        items: value.items
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: PaymentStatus;
    productName?: string;
    email?: string;
}): {
    status: [] | [_PaymentStatus];
    productName: [] | [string];
    email: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_PaymentStatus_n40(_uploadFile, _downloadFile, value.status)) : candid_none(),
        productName: value.productName ? candid_some(value.productName) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featured?: boolean;
    inStock?: boolean;
    name?: string;
    description?: string;
    imageUrl?: string;
    category?: Category;
    priceNPR?: bigint;
}): {
    featured: [] | [boolean];
    inStock: [] | [boolean];
    name: [] | [string];
    description: [] | [string];
    imageUrl: [] | [string];
    category: [] | [_Category];
    priceNPR: [] | [bigint];
} {
    return {
        featured: value.featured ? candid_some(value.featured) : candid_none(),
        inStock: value.inStock ? candid_some(value.inStock) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n14(_uploadFile, _downloadFile, value.category)) : candid_none(),
        priceNPR: value.priceNPR ? candid_some(value.priceNPR) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Streaming: null;
} | {
    Software: null;
} | {
    Gaming: null;
} {
    return value == Category.Streaming ? {
        Streaming: null
    } : value == Category.Software ? {
        Software: null
    } : value == Category.Gaming ? {
        Gaming: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    BankTransfer: null;
} | {
    ESewa: null;
} {
    return value == PaymentMethod.BankTransfer ? {
        BankTransfer: null
    } : value == PaymentMethod.ESewa ? {
        ESewa: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    UnderReview: null;
} | {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Processing: null;
} {
    return value == PaymentStatus.UnderReview ? {
        UnderReview: null
    } : value == PaymentStatus.Delivered ? {
        Delivered: null
    } : value == PaymentStatus.Confirmed ? {
        Confirmed: null
    } : value == PaymentStatus.Processing ? {
        Processing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
